### DISCUSSION TITLE
Automate Flutter CI/CD Pipeline for Build and Distribution with Firebase App Distribution

### DISCUSSION THREAD

**Discussion by nguyenvuong1309** [nguyenvuong1309/Blog#14] [General]
# Prepare file.
```
name: Android Build & Upload to Firebase App Distribution

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest  # Specify to use only Ubuntu
    timeout-minutes: 30

    steps:
      - name: 📥 Checkout code
        uses: actions/checkout@v3

      - name: ☕ Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: "zulu"
          java-version: "17.0.10"
          
      - name: 🧑‍💻 Check Java version
        run: java --version

      - name: 📂 Print Current Directory
        run: pwd
        
      - name: 🔑 Decode google-services.json
        env: 
          GOOGLE_SERVICES_JSON: ${{ secrets.GOOGLE_SERVICES_JSON }}
        run: echo "$GOOGLE_SERVICES_JSON" > android/app/google-services.json
        continue-on-error: true

      - name: 🔑 Decode Firebase options
        env:
          firebase_options_dart: ${{ secrets.FIREBASE_OPTION }}
        run: echo "$firebase_options_dart" > lib/firebase_options.dart
        continue-on-error: true

      - name: 🦄 Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          flutter-version: 3.24.1
        continue-on-error: true

      - name: 📋 Check Flutter Version
        run: flutter --version
        continue-on-error: true
      
      - name: 📦 Get Flutter dependencies
        run: flutter pub get
        continue-on-error: true

      - name: 📱 Build APK
        run: flutter build apk
        continue-on-error: true

      - name: 📤 Upload APK artifact
        uses: actions/upload-artifact@v1
        with:
          name: release-apk
          path: build/app/outputs/apk/release/app-release.apk
        continue-on-error: true

      - name: 🚀 Upload to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{ secrets.APPID }}
          token: ${{ secrets.TOKEN }}
          groups: tester
          file: build/app/outputs/apk/release/app-release.apk
        continue-on-error: true
```
# Prepare key.

- App id: Go to firebase project setting and get app id.
```
1:577087706126:android:c32f659f63a48eb329185f
```

![image](https://github.com/user-attachments/assets/c281aaad-4a7a-4da9-bcf0-0c8820d02eb1)

- Firebase option. ( Follow this link to learn how to add firebase in your project [Firebase documents](https://firebase.google.com/docs/flutter/setup?platform=ios)).
- Firebase token. (Folllow this link to learn how to get firebase token [Firebase token](https://github.com/nguyenvuong1309/Blog/discussions/12)).
- Google service : Download from project setting in firebase.

![image](https://github.com/user-attachments/assets/bb96088c-bc02-4df7-b02c-b8e1aece0272)

# Add key to github.

- Go to github setting, `Secrets and variables` part.

![image](https://github.com/user-attachments/assets/c6f079de-c9a5-4a37-a647-3d3aa28ee084)

- Add key.

![image](https://github.com/user-attachments/assets/b66b2114-cb54-4124-8d8d-dbdae80f7a4c)

# Add group tester in firebase.

- First you need to enable firebase app distribution, then add a goup tester with name `tester`.
- Add email of user that you want to add to group tester.

![image](https://github.com/user-attachments/assets/df7b14a3-1f9e-45fe-8d99-3da5c821cec6)
